SET IMPLICIT_TRANSACTIONS OFF;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION

SELECT TOP 3 * FROM Rachunki
ORDER BY Rachunki.id DESC
UPDATE Rachunki
SET Saldo_Aktualne=1000, Saldo_Wplat=1000
WHERE Rachunki.id=7

COMMIT TRANSACTION